
CREATE TABLE RB_USER (
	ID					BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER			VARCHAR2(50) NOT NULL,
	CREATE_TIME			TIMESTAMP NOT NULL,
	MODIFY_USER			VARCHAR2(50) NOT NULL,
	MODIFY_TIME			TIMESTAMP NOT NULL,
	SYS_STATUS			CHAR(1) NOT NULL,
	
	CODE				VARCHAR2(50) NOT NULL,
	NAME				NVARCHAR(100),
	PASSWORD			VARCHAR2(50) NOT NULL,
	DESCRIPTION			NVARCHAR(1000),
	
	FIRST_LOGIN_TIME	TIMESTAMP,
	LAST_LOGIN_TIME		TIMESTAMP,
	LOGIN_COUNT			INT NOT NULL,
	ERROR_COUNT			INT NOT NULL,
	
	EXPIRE_TIME			TIMESTAMP NOT NULL,
	IS_LOCK				BOOLEAN NOT NULL
);
CREATE UNIQUE INDEX IDX_CODE ON RB_USER (CODE);