
INSERT INTO rb_user (ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS, CODE, NAME, PASSWORD, DESCRIPTION, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, LOGIN_COUNT, ERROR_COUNT, EXPIRE_TIME, IS_LOCK)
VALUES (1, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y', 'admin', 'admin', 'admin123', 'administrator', null, null, 0, 0, '2099-01-01 00:00:00', FALSE);

INSERT INTO rb_user (ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS, CODE, NAME, PASSWORD, DESCRIPTION, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, LOGIN_COUNT, ERROR_COUNT, EXPIRE_TIME, IS_LOCK)
VALUES (2, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y', 'user', 'user', 'user123', 'general user', null, null, 0, 0, '2099-01-01 00:00:00', FALSE);
