-- ==================================================================
-- SAMPLE DATA
-- ==================================================================

-- USER
INSERT INTO rb_user (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	CODE, NAME, DESCRIPTION,
	PASSWORD, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, LOGIN_COUNT, ERROR_COUNT, EXPIRE_TIME, LOCK_STATUS)
VALUES (
	1, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y',
	'admin', 'admin', 'administrator', 
	'$2a$10$.mAivHSvvrO9MkQ77lGD5.WxVmj75qQG7dqcxzL2vRgr/IJOQmZqu', null, null, 0, 0, '2100-01-01 00:00:00', 'N'
);

INSERT INTO rb_user (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	CODE, NAME, DESCRIPTION,
	PASSWORD, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, LOGIN_COUNT, ERROR_COUNT, EXPIRE_TIME, LOCK_STATUS)
VALUES (
	2, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y',
	'user', 'user', 'general user', 
	'$2a$10$749VfAYgJXAQm3FsOM4ixu8ItEC9cjwf0yAhEKdmJbvY6i.7u2nLC', null, null, 0, 0, '2100-01-01 00:00:00', 'N'
);


-- ROLE
INSERT INTO rb_role (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	CODE, NAME, DESCRIPTION)
VALUES (
	1, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y',
	'ROLE_ADMIN', 'admin', 'admin'
);

INSERT INTO rb_role (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	CODE, NAME, DESCRIPTION)
VALUES (
	2, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y',
	'ROLE_USER', 'user', 'user'
);


-- USER_ROLE
INSERT INTO rb_user_role (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	USER_ID, ROLE_ID)
VALUES (
	1, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y',
	1, 1
);

INSERT INTO rb_user_role (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	USER_ID, ROLE_ID)
VALUES (
	2, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y',
	1, 2
);

INSERT INTO rb_user_role (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	USER_ID, ROLE_ID)
VALUES (
	3, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y',
	2, 2
);
