
INSERT INTO rb_user (ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS, CODE, NAME, PASSWORD, DESCRIPTION, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, LOGIN_COUNT, ERROR_COUNT)
VALUES (1, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y', 'admin', 'admin', 'admin123', 'administrator', null, null, 0, 0);

INSERT INTO rb_user (ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS, CODE, NAME, PASSWORD, DESCRIPTION, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, LOGIN_COUNT, ERROR_COUNT)
VALUES (2, 'TEST', CURRENT_TIMESTAMP(), 'TEST', CURRENT_TIMESTAMP(), 'Y', 'user', 'user', 'user123', 'general user', null, null, 0, 0);
